name: autoservice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  get: ^3.13.2
  intl: 
  flutter_staggered_animations: 
  
  shared_preferences: ^0.5.4
  #http: ^0.12.0+2
  fdottedline: ^1.0.1
  cached_network_image: ^2.2.0+1
  dotted_border: ^1.0.7
  flutter_svg: 
  dio: ^3.0.7
  flutter_spinkit: 
  intl_phone_number_input: ^0.6.0
  flutter_sim_country_code: ^0.0.3
  image_picker: ^0.6.7+4
  rounded_loading_button: ^1.0.0
  sim_info: ^0.1.2
  shimmer: ^1.1.2
  fluttertoast: ^7.1.6
  rflutter_alert: ^1.1.0
  pin_code_fields: ^6.1.0
  url_launcher: 
  photo_view:
  flutter_inappwebview: 4.0.0+4
  assets_audio_player: 
  record: 
  carousel_slider: 1.3.0
  flutter_launcher_icons: ^0.7.5
  permission_handler:
  stop_watch_timer:
  get_storage:
  swipe_to:
  toast:
  firebase_analytics: ^5.0.11
  flutter_local_notifications: ^4.0.1
  socket_io_client: ^0.9.12
  firebase_core: ^0.5.3
  firebase_messaging: 5.1.2
  scroll_to_index:
  flutter_widget_from_html: ^0.5.2+1
  agora_rtc_engine: 3.3.2
  flutter_countdown_timer: 
  add_cart_parabola: ^0.0.6  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
    image_path: "assets/images/luncher.png"
    android : true
    ios : true
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
      # - assets/locales/
      - assets/images/icons/Menu/Support.png
      - assets/images/Empty.png
      - assets/images/1.jpeg
      - assets/images/2.jpeg
      - assets/images/BlueCar.png
      - assets/images/delete.svg
      - assets/images/check_crircle.svg
      - assets/images/ic_delete.svg
      - assets/images/ic_pencil.svg
      - assets/images/home.svg
      - assets/images/user.svg
      - assets/images/Image1.png
      - assets/images/Image5.png
      - assets/images/Image6.png
      - assets/images/Image11.png
      - assets/images/Image8.png
      - assets/images/Group5.png
      - assets/images/Group786.png
      - assets/images/spare-parts.png
      - assets/images/company.png
      - assets/images/call.png
      - assets/images/icons/Home/Group224@3x.png
      - assets/images/icons/Home/Group233@3x.png
      - assets/images/icons/Home/Group225@3x.png
      - assets/images/icons/Home/Group226@3x.png
      - assets/images/icons/Home/Group232@3x.png
      - assets/images/icons/Home/Group227@3x.png
      - assets/images/icons/Cars/cars(1).png
      - assets/images/icons/Cars/cars(2).png
      - assets/images/icons/Cars/cars(3).png
      - assets/images/icons/Menu/gordini@3x.png
      - assets/images/icons/Menu/Group720@3x.png
      - assets/images/icons/Menu/Group721@3x.png
      - assets/images/icons/Menu/Group722@3x.png
      - assets/images/icons/Menu/Group724@3x.png
      - assets/images/icons/Menu/Group726@3x.png
      - assets/images/icons/Menu/Group815@3x.png
      - assets/images/icons/Menu/home@3x.png
      - assets/images/icons/Menu/Path4636@3x.png
      - assets/images/icons/Menu/user@3x.png
      - assets/images/icons/Scrap/scrap(1).png
      - assets/images/icons/Scrap/scrap(2).png
      - assets/images/icons/Scrap/scrap(3).png
      - assets/images/icons/Scrap/scrap(4).png
      - assets/images/icons/Scrap/scrap(5).png
      - assets/images/icons/Scrap/scrap(6).png
      - assets/images/icons/Scrap/scrap(7).png
      - assets/images/icons/Scrap/scrap(8).png
      - assets/images/icons/Scrap/scrap(9).png
      - assets/images/icons/Scrap/scrap(10).png
      - assets/images/icons/Scrap/scrap(11).png
      - assets/images/icons/Ta2min/Ta3min(1).png
      - assets/images/icons/Ta2min/Ta3min(2).png
      - assets/images/icons/Ta2min/Ta3min(3).png
      - assets/images/icons/Ta2min/Ta3min(4).png
      - assets/images/icons/Ta2min/Ta3min(5).png
      - assets/images/icons/Ta2min/Ta3min(6).png
      - assets/images/icons/Ta2min/Ta3min(7).png
      - assets/images/icons/Ta2min/Ta3min(8).png
      - assets/images/icons/Ta2min/Ta3min(9).png
      - assets/images/icons/Ta2min/Ta3min(10).png
      - assets/images/icons/Acs/Acs(1).png
      - assets/images/icons/Acs/Acs(2).png
      - assets/images/icons/Acs/Acs(3).png
      - assets/images/icons/Acs/Acs(4).png
      - assets/images/icons/Acs/Acs(5).png
      - assets/images/icons/Acs/Acs(6).png
      - assets/images/icons/Acs/Acs(7).png
      - assets/images/icons/Acs/Acs(8).png
      - assets/images/icons/Acs/Acs(9).png
      - assets/images/icons/Acs/Acs(10).png
      - assets/images/icons/Acs/Acs(11).png
      - assets/images/icons/Acs/Acs(12).png
      - assets/images/icons/Acs/Acs(13).png
      - assets/images/icons/Acs/Acs(14).png
      - assets/images/emptyFavorit.png
      - assets/images/emptymoshtryat.png
      - assets/images/luncher.png
      - assets/images/App-Splash.png
      - assets/images/voice.gif
      - assets/images/sa.png
      - assets/images/chat-icons/
      - assets/images/qa.png
      - assets/images/kw.png
      - assets/images/icons/Menu/Language.png
      - assets/sounds/voice_call_end.mp3
      - assets/sounds/voice_call_start.mp3
      - assets/sounds/text_tone.mp3
      - assets/sounds/record_tone.mp3
      - assets/sounds/incomingcall.mp3
      - assets/sounds/sound.mp3

 

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
        

    - family: Scheherazade
      fonts:
        - asset: assets/fonts/Scheherazade-Regular.ttf